// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckHealth() {
  return window['go']['main']['App']['CheckHealth']();
}

export function GetAgents() {
  return window['go']['main']['App']['GetAgents']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetModels() {
  return window['go']['main']['App']['GetModels']();
}

export function GetProviders() {
  return window['go']['main']['App']['GetProviders']();
}

export function GetRecentSessions() {
  return window['go']['main']['App']['GetRecentSessions']();
}

export function GetSkills(arg1) {
  return window['go']['main']['App']['GetSkills'](arg1);
}

export function SendAgentMessage(arg1, arg2) {
  return window['go']['main']['App']['SendAgentMessage'](arg1, arg2);
}

export function SendMessage(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SendMessage'](arg1, arg2, arg3, arg4);
}

export function StartPilot() {
  return window['go']['main']['App']['StartPilot']();
}

export function StopPilot() {
  return window['go']['main']['App']['StopPilot']();
}
