// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {client} from '../models';
import {main} from '../models';

export function CheckHealth():Promise<boolean>;

export function GetAgents():Promise<Array<client.Agent>>;

export function GetConfig():Promise<main.AppConfig>;

export function GetModels():Promise<Array<client.Model>>;

export function GetProviders():Promise<Array<client.Provider>>;

export function GetRecentSessions():Promise<Array<string>>;

export function GetSkills(arg1:string):Promise<Array<client.Skill>>;

export function SendAgentMessage(arg1:string,arg2:string):Promise<void>;

export function SendMessage(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function StartPilot():Promise<void>;

export function StopPilot():Promise<void>;
